### ISSUE TITLE
About KITTI train dataset generalization results

### ISSUE THREAD

**Issue by gangweix** [haofeixu/flow1d#5]
Hi, I use your open source code and the pre-trained model you gave to test kitti's training set.
![f03ee242115707fc9498243b1011b40](https://user-images.githubusercontent.com/34023118/207232962-667db763-6b4a-4327-b16e-58935c8585ef.png)
But in the paper, the reported result is EPE: 6.69, F1-all: 22.95, the iteration number is the same.

**Comment by gangweix** [comment]
Is there something wrong with my test?

**Comment by haofeixu** [comment]
Hi, are you able to get the same numbers as ours on Sintel?

**Comment by gangweix** [comment]
No, I can't. The results I test is 1.97 (clean) and 3.47 (final).
![1670917765336](https://user-images.githubusercontent.com/34023118/207257008-f3bde855-f3e1-492c-a06b-cf2d76795535.png)

And, I also test RAFT. When iteration number is 12, the result on KITTI is,
![1670917856599](https://user-images.githubusercontent.com/34023118/207257279-4cd4699d-65bd-4130-81bb-1024613a5119.png)

When the iteration number is 24, the result on KITTI is,
![1670917909244](https://user-images.githubusercontent.com/34023118/207257468-eca7119f-fdac-4062-83b1-186a02ab66ca.png)

Looking forward to your reply！

**Comment by haofeixu** [comment]
Just did a quick test, I can perfectly reproduce the numbers (24 iters for KITTI and 32 for Sintel):
```
Validation KITTI EPE: 6.690, F1-all: 22.952
Validation Sintel (clean) EPE: 1.978, 1px: 0.129, 3px: 0.056, 5px: 0.040
Validation Sintel (final) EPE: 3.266, 1px: 0.177, 3px: 0.096, 5px: 0.073
```
Are you using our code for testing, and are you using our environment (seems that you are running `evaluate.py` with `stereo` env which are different from our code)?

**Comment by gangweix** [comment]
It should be caused by me, when I switch the iteration number from 12 to 24, it can output the same result as in the paper. 
![1670922242912](https://user-images.githubusercontent.com/34023118/207274003-eb3fc99c-ab66-4744-8f90-9b069307c1fb.png)

Thanks!
